name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # Needed for GitHub Releases

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cross
        run: cargo install cross

      - name: Build Windows release using cross
        run: cross build --release --target x86_64-pc-windows-gnu

      - name: Zip binary
        run: zip nbt-quadrant-windows.zip target/x86_64-pc-windows-gnu/release/nbt-quadrant.exe

      - name: Upload release ZIP
        uses: softprops/action-gh-release@v2
        with:
          files: nbt-quadrant-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
