name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers only on version tags like v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions/setup-rust@v1.8.0

      - name: Build
        run: cargo build --release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/nbt-quadrant.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
